/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sm.mainFrame;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.Timer;
import sm.jPanelManager.classes.JPClassManager;
import sm.jPanelManager.room.JPRoomManager;
import sm.jPanelManager.score.JPScoreManager;
import sm.jPanelManager.student.JPStudentManager;
import sm.jPanelManager.student.StudentDAO;
import sm.jPanelManager.subject.JPSubjectManager;
import sm.jPanelManager.teacher.JPTeacherManager;
import sm.jPanelManager.timetable.JPTimetableManager;
import sm.jPanelManager.user.JPPerManager;
import sm.jPanelManager.user.JPUserManager;
import sm.jPanelManager.recycle.JPRecycle;

/**
 *
 * @author Ngoc Tuan
 */
public class MainFrame extends javax.swing.JFrame {

    private static JPStudentManager jPStudentManager;
    private JPTeacherManager jPTeacherManager;
    private static JPClassManager jPClassManager;
    private JPSubjectManager jPSubjectManager;
    private JPRoomManager jPRoomManager;
    private static JPScoreManager jPScoreManager;
    private static JPTimetableManager jPTimetableManager;
    private static JPUserManager jPUserManager;
    private static JPPerManager jPPerManager;
    private static JPRecycle jPRecycle;

    private StudentDAO studentDAO = new StudentDAO();

    /**
     * Creates new form NewJFrame
     */
    public MainFrame() {
        initComponents();

        jSplitPane1.setDividerLocation(60);
        jLabelLogo1.setVisible(false);
        jLabelTextLogo1.setVisible(false);
        jLabelMenu3.setVisible(false);
        jLabelMenu2.setVisible(true);

        jLabelLineClasses.setVisible(false);
        jLabelLineRoom.setVisible(false);
        jLabelLineScore.setVisible(false);
        jLabelLineStudent.setVisible(false);
        jLabelLineSubject.setVisible(false);
        jLabelLineTeacher.setVisible(false);
        jLabelLineTimetable.setVisible(false);
        jLabelLineUser.setVisible(false);

        timeNow();

        addJPanelManager();
    }

    public static JPPerManager getjPPerManager() {
        return jPPerManager;
    }

    public static JPUserManager getjPUserManager() {
        return jPUserManager;
    }

    public static JPRecycle getjPRecycle() {
        return jPRecycle;
    }

    public static JPClassManager getjPClassManager() {
        return jPClassManager;
    }

    public static JPStudentManager getjPStudentManager() {
        return jPStudentManager;
    }

    public static JPScoreManager getjPScoreManager() {
        return jPScoreManager;
    }

    public static JPTimetableManager getjPTimetableManager() {
        return jPTimetableManager;
    }

    private void timeNow() {
        new Timer(0, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                DateTimeFormatter dtf = DateTimeFormatter.ofPattern("HH:mm:ss a");
                LocalDateTime now = LocalDateTime.now();
                jLabelTime2.setText(String.valueOf(dtf.format(now)));
            }
        }).start();
    }

    private void addJPanelManager() {
        jPStudentManager = new JPStudentManager();
        jPanelContent.add(jPStudentManager);

        jPTeacherManager = new JPTeacherManager();
        jPanelContent.add(jPTeacherManager);

        jPClassManager = new JPClassManager();
        jPanelContent.add(jPClassManager);

        jPSubjectManager = new JPSubjectManager();
        jPanelContent.add(jPSubjectManager);

        jPRoomManager = new JPRoomManager();
        jPanelContent.add(jPRoomManager);

        jPScoreManager = new JPScoreManager();
        jPanelContent.add(jPScoreManager);

        jPTimetableManager = new JPTimetableManager();
        jPanelContent.add(jPTimetableManager);

        jPUserManager = new JPUserManager();
        jPanelContent.add(jPUserManager);

        jPPerManager = new JPPerManager();
        jPanelContent.add(jPPerManager);

        jPRecycle = new JPRecycle();
        jPanelContent.add(jPRecycle);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanelLeft = new javax.swing.JPanel();
        jPanelTop1 = new javax.swing.JPanel();
        jLabelLogo1 = new javax.swing.JLabel();
        jLabelTextLogo1 = new javax.swing.JLabel();
        jLabelMenu2 = new javax.swing.JLabel();
        jLabelMenu3 = new javax.swing.JLabel();
        jLabelHome = new javax.swing.JLabel();
        jLabelScore = new javax.swing.JLabel();
        jLabelStudent = new javax.swing.JLabel();
        jLabelTeacher = new javax.swing.JLabel();
        jLabelClass = new javax.swing.JLabel();
        jLabelSubject = new javax.swing.JLabel();
        jLabelTimetable = new javax.swing.JLabel();
        jLabelRoom = new javax.swing.JLabel();
        jLabelUser = new javax.swing.JLabel();
        jLabelLineHome = new javax.swing.JLabel();
        jLabelLineStudent = new javax.swing.JLabel();
        jLabelLineTeacher = new javax.swing.JLabel();
        jLabelLineScore = new javax.swing.JLabel();
        jLabelLineClasses = new javax.swing.JLabel();
        jLabelLineSubject = new javax.swing.JLabel();
        jLabelLineTimetable = new javax.swing.JLabel();
        jLabelLineRoom = new javax.swing.JLabel();
        jLabelLineUser = new javax.swing.JLabel();
        jPanelRight = new javax.swing.JPanel();
        jPanelMid = new javax.swing.JPanel();
        jLabelWelcome = new javax.swing.JLabel();
        jLabelRole = new javax.swing.JLabel();
        jLabelTime2 = new javax.swing.JLabel();
        jPanelTop = new javax.swing.JPanel();
        jLabelGroup4 = new javax.swing.JLabel();
        jLabelSetting = new javax.swing.JLabel();
        jLabelShutdown = new javax.swing.JLabel();
        jPanelContent = new javax.swing.JPanel();
        jPanelHome = new javax.swing.JPanel();
        jPanelTotalClass = new javax.swing.JPanel();
        jLabelTotalClass = new javax.swing.JLabel();
        jLabelCountClass = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanelTotalStudent = new javax.swing.JPanel();
        jLabelTotalStudent = new javax.swing.JLabel();
        jLabelCountStudent = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanelTotalTeacher = new javax.swing.JPanel();
        jLabelTotalTeacher = new javax.swing.JLabel();
        jLabelCountTeacher = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanelLabelHome = new javax.swing.JPanel();
        jLabelHome1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanelStatisticsGender = new javax.swing.JPanel();
        jPanelStatisticsAvgScore = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);

        jSplitPane1.setBackground(new java.awt.Color(255, 255, 255));
        jSplitPane1.setDividerLocation(231);
        jSplitPane1.setDividerSize(0);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jPanelLeft.setBackground(new java.awt.Color(255, 255, 255));
        jPanelLeft.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanelLeftMouseMoved(evt);
            }
        });

        jPanelTop1.setBackground(new java.awt.Color(255, 255, 255));

        jLabelLogo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sm/image/iconfinder_Student_1170240.png"))); // NOI18N

        jLabelTextLogo1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelTextLogo1.setText("Student Manager R2B");

        jLabelMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sm/image/menu2.png"))); // NOI18N
        jLabelMenu2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMenu2jLabelMenu1MouseClicked(evt);
            }
        });

        jLabelMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sm/image/menu2.png"))); // NOI18N
        jLabelMenu3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMenu3jLabelMenuMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelTop1Layout = new javax.swing.GroupLayout(jPanelTop1);
        jPanelTop1.setLayout(jPanelTop1Layout);
        jPanelTop1Layout.setHorizontalGroup(
            jPanelTop1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTop1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelTop1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelTop1Layout.createSequentialGroup()
                        .addComponent(jLabelMenu2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelLogo1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                        .addComponent(jLabelMenu3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTop1Layout.createSequentialGroup()
                        .addComponent(jLabelTextLogo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanelTop1Layout.setVerticalGroup(
            jPanelTop1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTop1Layout.createSequentialGroup()
                .addGroup(jPanelTop1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelTop1Layout.createSequentialGroup()
                        .addGroup(jPanelTop1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelTop1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabelMenu2))
                            .addComponent(jLabelMenu3))
                        .addGap(0, 78, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTop1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabelLogo1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelTextLogo1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );

        jLabelHome.setBackground(new java.awt.Color(255, 255, 255));
        jLabelHome.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jLabelHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sm/image/dashboard.png"))); // NOI18N
        jLabelHome.setText("<html><div style='text-align: right;'>&emsp;&emsp;Home</div></html> ");
        jLabelHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelHome.setOpaque(true);
        jLabelHome.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabelHomeMouseMoved(evt);
            }
        });
        jLabelHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelHomeMouseClicked(evt);
            }
        });

        jLabelScore.setBackground(new java.awt.Color(255, 255, 255));
        jLabelScore.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jLabelScore.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sm/image/score1.png"))); // NOI18N
        jLabelScore.setText("<html><div style='text-align: right;'>&emsp;&emsp;Score</div></html> ");
        jLabelScore.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelScore.setOpaque(true);
        jLabelScore.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabelScoreMouseMoved(evt);
            }
        });
        jLabelScore.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelScoreMouseClicked(evt);
            }
        });

        jLabelStudent.setBackground(new java.awt.Color(255, 255, 255));
        jLabelStudent.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jLabelStudent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sm/image/student1.png"))); // NOI18N
        jLabelStudent.setText("<html><div style='text-align: right;'>&emsp;&emsp;Student</div></html> ");
        jLabelStudent.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelStudent.setOpaque(true);
        jLabelStudent.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabelStudentMouseMoved(evt);
            }
        });
        jLabelStudent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelStudentMouseClicked(evt);
            }
        });

        jLabelTeacher.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTeacher.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jLabelTeacher.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sm/image/teacher1.png"))); // NOI18N
        jLabelTeacher.setText("<html><div style='text-align: right;'>&emsp;&emsp;Teacher</div></html> ");
        jLabelTeacher.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelTeacher.setOpaque(true);
        jLabelTeacher.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabelTeacherMouseMoved(evt);
            }
        });
        jLabelTeacher.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelTeacherMouseClicked(evt);
            }
        });

        jLabelClass.setBackground(new java.awt.Color(255, 255, 255));
        jLabelClass.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jLabelClass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sm/image/class1.png"))); // NOI18N
        jLabelClass.setText("<html><div style='text-align: right;'>&emsp;&emsp;Classes</div></html> ");
        jLabelClass.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelClass.setOpaque(true);
        jLabelClass.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabelClassMouseMoved(evt);
            }
        });
        jLabelClass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelClassMouseClicked(evt);
            }
        });

        jLabelSubject.setBackground(new java.awt.Color(255, 255, 255));
        jLabelSubject.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jLabelSubject.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sm/image/subject1.png"))); // NOI18N
        jLabelSubject.setText("<html><div style='text-align: right;'>&emsp;&emsp;Subjects</div></html> ");
        jLabelSubject.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelSubject.setOpaque(true);
        jLabelSubject.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabelSubjectMouseMoved(evt);
            }
        });
        jLabelSubject.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelSubjectMouseClicked(evt);
            }
        });

        jLabelTimetable.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTimetable.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jLabelTimetable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sm/image/timetable1.png"))); // NOI18N
        jLabelTimetable.setText("<html><div style='text-align: right;'>&emsp;&emsp;Timetable</div></html> ");
        jLabelTimetable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelTimetable.setOpaque(true);
        jLabelTimetable.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabelTimetableMouseMoved(evt);
            }
        });
        jLabelTimetable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelTimetableMouseClicked(evt);
            }
        });

        jLabelRoom.setBackground(new java.awt.Color(255, 255, 255));
        jLabelRoom.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jLabelRoom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sm/image/room1.png"))); // NOI18N
        jLabelRoom.setText("<html><div style='text-align: right;'>&emsp;&emsp;Room</div></html> ");
        jLabelRoom.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelRoom.setOpaque(true);
        jLabelRoom.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabelRoomMouseMoved(evt);
            }
        });
        jLabelRoom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelRoomMouseClicked(evt);
            }
        });

        jLabelUser.setBackground(new java.awt.Color(255, 255, 255));
        jLabelUser.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jLabelUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sm/image/setting1.png"))); // NOI18N
        jLabelUser.setText("<html><div style='text-align: right;'>&emsp;&emsp;User</div></html> ");
        jLabelUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelUser.setOpaque(true);
        jLabelUser.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabelUserMouseMoved(evt);
            }
        });
        jLabelUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelUserMouseClicked(evt);
            }
        });

        jLabelLineHome.setBackground(new java.awt.Color(51, 51, 51));
        jLabelLineHome.setOpaque(true);
        jLabelLineHome.setPreferredSize(new java.awt.Dimension(6, 6));

        jLabelLineStudent.setBackground(new java.awt.Color(51, 51, 51));
        jLabelLineStudent.setOpaque(true);
        jLabelLineStudent.setPreferredSize(new java.awt.Dimension(5, 5));

        jLabelLineTeacher.setBackground(new java.awt.Color(51, 51, 51));
        jLabelLineTeacher.setOpaque(true);
        jLabelLineTeacher.setPreferredSize(new java.awt.Dimension(5, 5));

        jLabelLineScore.setBackground(new java.awt.Color(51, 51, 51));
        jLabelLineScore.setOpaque(true);
        jLabelLineScore.setPreferredSize(new java.awt.Dimension(5, 5));

        jLabelLineClasses.setBackground(new java.awt.Color(51, 51, 51));
        jLabelLineClasses.setOpaque(true);
        jLabelLineClasses.setPreferredSize(new java.awt.Dimension(5, 5));

        jLabelLineSubject.setBackground(new java.awt.Color(51, 51, 51));
        jLabelLineSubject.setOpaque(true);
        jLabelLineSubject.setPreferredSize(new java.awt.Dimension(5, 5));

        jLabelLineTimetable.setBackground(new java.awt.Color(51, 51, 51));
        jLabelLineTimetable.setOpaque(true);
        jLabelLineTimetable.setPreferredSize(new java.awt.Dimension(5, 5));

        jLabelLineRoom.setBackground(new java.awt.Color(51, 51, 51));
        jLabelLineRoom.setOpaque(true);
        jLabelLineRoom.setPreferredSize(new java.awt.Dimension(5, 5));

        jLabelLineUser.setBackground(new java.awt.Color(51, 51, 51));
        jLabelLineUser.setOpaque(true);
        jLabelLineUser.setPreferredSize(new java.awt.Dimension(5, 5));

        javax.swing.GroupLayout jPanelLeftLayout = new javax.swing.GroupLayout(jPanelLeft);
        jPanelLeft.setLayout(jPanelLeftLayout);
        jPanelLeftLayout.setHorizontalGroup(
            jPanelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelTop1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelLeftLayout.createSequentialGroup()
                .addGroup(jPanelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabelLineUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelLineHome, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelLineStudent, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelLineTeacher, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelLineScore, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelLineClasses, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelLineSubject, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelLineTimetable, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelLineRoom, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelHome)
                    .addComponent(jLabelStudent)
                    .addComponent(jLabelTeacher)
                    .addComponent(jLabelScore)
                    .addComponent(jLabelClass)
                    .addComponent(jLabelSubject)
                    .addComponent(jLabelTimetable)
                    .addComponent(jLabelRoom)
                    .addComponent(jLabelUser)))
        );
        jPanelLeftLayout.setVerticalGroup(
            jPanelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLeftLayout.createSequentialGroup()
                .addComponent(jPanelTop1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(jPanelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelLineHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelHome))
                .addGap(18, 18, 18)
                .addGroup(jPanelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelLineStudent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelStudent))
                .addGap(18, 18, 18)
                .addGroup(jPanelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelLineTeacher, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelTeacher))
                .addGap(18, 18, 18)
                .addGroup(jPanelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelLineScore, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelScore))
                .addGap(18, 18, 18)
                .addGroup(jPanelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelLineClasses, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelClass))
                .addGap(18, 18, 18)
                .addGroup(jPanelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelSubject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelLineSubject, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTimetable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelLineTimetable, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelRoom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelLineRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelLineUser, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(95, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanelLeft);

        jSplitPane1.setLeftComponent(jScrollPane1);

        jPanelRight.setBackground(new java.awt.Color(255, 255, 255));

        jPanelMid.setBackground(new java.awt.Color(255, 255, 255));

        jLabelWelcome.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jLabelWelcome.setText("Welcome:");

        jLabelRole.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jLabelRole.setText("Role:");

        jLabelTime2.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jLabelTime2.setText("HH:MM:SS");

        javax.swing.GroupLayout jPanelMidLayout = new javax.swing.GroupLayout(jPanelMid);
        jPanelMid.setLayout(jPanelMidLayout);
        jPanelMidLayout.setHorizontalGroup(
            jPanelMidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMidLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabelRole)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 710, Short.MAX_VALUE)
                .addComponent(jLabelTime2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanelMidLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabelWelcome)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelMidLayout.setVerticalGroup(
            jPanelMidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMidLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabelWelcome)
                .addGap(17, 17, 17)
                .addComponent(jLabelRole)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMidLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelTime2)
                .addGap(31, 31, 31))
        );

        jLabelGroup4.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jLabelGroup4.setText("R2B");

        jLabelSetting.setBackground(new java.awt.Color(53, 173, 164));
        jLabelSetting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sm/image/setting2.png"))); // NOI18N
        jLabelSetting.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabelShutdown.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sm/image/sshutdown1.png"))); // NOI18N
        jLabelShutdown.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelShutdown.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelShutdownMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelTopLayout = new javax.swing.GroupLayout(jPanelTop);
        jPanelTop.setLayout(jPanelTopLayout);
        jPanelTopLayout.setHorizontalGroup(
            jPanelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTopLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabelGroup4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelSetting)
                .addGap(18, 18, 18)
                .addComponent(jLabelShutdown, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelTopLayout.setVerticalGroup(
            jPanelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelGroup4)
            .addComponent(jLabelShutdown)
            .addComponent(jLabelSetting)
        );

        jPanelContent.setBackground(new java.awt.Color(255, 255, 255));

        jPanelTotalClass.setBackground(new java.awt.Color(255, 255, 255));

        jLabelTotalClass.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTotalClass.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabelTotalClass.setText("Total Classes");
        jLabelTotalClass.setOpaque(true);

        jLabelCountClass.setBackground(new java.awt.Color(255, 255, 255));
        jLabelCountClass.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabelCountClass.setText("50");
        jLabelCountClass.setOpaque(true);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sm/image/class.png"))); // NOI18N

        javax.swing.GroupLayout jPanelTotalClassLayout = new javax.swing.GroupLayout(jPanelTotalClass);
        jPanelTotalClass.setLayout(jPanelTotalClassLayout);
        jPanelTotalClassLayout.setHorizontalGroup(
            jPanelTotalClassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTotalClassLayout.createSequentialGroup()
                .addGroup(jPanelTotalClassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelTotalClassLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabelCountClass, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelTotalClassLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelTotalClass, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanelTotalClassLayout.setVerticalGroup(
            jPanelTotalClassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTotalClassLayout.createSequentialGroup()
                .addGroup(jPanelTotalClassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelTotalClassLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelTotalClass, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelCountClass, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelTotalClassLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel4)))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanelTotalStudent.setBackground(new java.awt.Color(255, 255, 255));

        jLabelTotalStudent.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTotalStudent.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabelTotalStudent.setText("Total Students");
        jLabelTotalStudent.setOpaque(true);

        jLabelCountStudent.setBackground(new java.awt.Color(255, 255, 255));
        jLabelCountStudent.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabelCountStudent.setText("50");
        jLabelCountStudent.setOpaque(true);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sm/image/student.png"))); // NOI18N

        javax.swing.GroupLayout jPanelTotalStudentLayout = new javax.swing.GroupLayout(jPanelTotalStudent);
        jPanelTotalStudent.setLayout(jPanelTotalStudentLayout);
        jPanelTotalStudentLayout.setHorizontalGroup(
            jPanelTotalStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTotalStudentLayout.createSequentialGroup()
                .addGroup(jPanelTotalStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelTotalStudentLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabelCountStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelTotalStudentLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelTotalStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelTotalStudentLayout.setVerticalGroup(
            jPanelTotalStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTotalStudentLayout.createSequentialGroup()
                .addGroup(jPanelTotalStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelTotalStudentLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelTotalStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelCountStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelTotalStudentLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel7)))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanelTotalTeacher.setBackground(new java.awt.Color(255, 255, 255));

        jLabelTotalTeacher.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTotalTeacher.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabelTotalTeacher.setText("Total Teachers");
        jLabelTotalTeacher.setOpaque(true);

        jLabelCountTeacher.setBackground(new java.awt.Color(255, 255, 255));
        jLabelCountTeacher.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabelCountTeacher.setText("50");
        jLabelCountTeacher.setOpaque(true);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sm/image/teacher.png"))); // NOI18N

        javax.swing.GroupLayout jPanelTotalTeacherLayout = new javax.swing.GroupLayout(jPanelTotalTeacher);
        jPanelTotalTeacher.setLayout(jPanelTotalTeacherLayout);
        jPanelTotalTeacherLayout.setHorizontalGroup(
            jPanelTotalTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTotalTeacherLayout.createSequentialGroup()
                .addGroup(jPanelTotalTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelTotalTeacherLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabelCountTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelTotalTeacherLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelTotalTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanelTotalTeacherLayout.setVerticalGroup(
            jPanelTotalTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTotalTeacherLayout.createSequentialGroup()
                .addGroup(jPanelTotalTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelTotalTeacherLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelTotalTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelCountTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelTotalTeacherLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel10)))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanelLabelHome.setBackground(new java.awt.Color(153, 153, 153));

        jLabelHome1.setBackground(new java.awt.Color(153, 153, 153));
        jLabelHome1.setFont(new java.awt.Font("Century Gothic", 1, 22)); // NOI18N
        jLabelHome1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelHome1.setText("<html><div style='text-align: right;'>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;Student Manager Overview</div></html> ");
        jLabelHome1.setOpaque(true);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setOpaque(true);
        jLabel1.setPreferredSize(new java.awt.Dimension(5, 5));

        javax.swing.GroupLayout jPanelLabelHomeLayout = new javax.swing.GroupLayout(jPanelLabelHome);
        jPanelLabelHome.setLayout(jPanelLabelHomeLayout);
        jPanelLabelHomeLayout.setHorizontalGroup(
            jPanelLabelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLabelHomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelHome1)
                .addContainerGap())
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelLabelHomeLayout.setVerticalGroup(
            jPanelLabelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLabelHomeLayout.createSequentialGroup()
                .addComponent(jLabelHome1, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanelStatisticsGender.setBackground(new java.awt.Color(255, 51, 0));
        jPanelStatisticsGender.setLayout(new java.awt.BorderLayout());

        jPanelStatisticsAvgScore.setBackground(new java.awt.Color(255, 0, 0));
        jPanelStatisticsAvgScore.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout jPanelHomeLayout = new javax.swing.GroupLayout(jPanelHome);
        jPanelHome.setLayout(jPanelHomeLayout);
        jPanelHomeLayout.setHorizontalGroup(
            jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelLabelHome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelHomeLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelHomeLayout.createSequentialGroup()
                        .addComponent(jPanelStatisticsAvgScore, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanelStatisticsGender, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))
                    .addGroup(jPanelHomeLayout.createSequentialGroup()
                        .addComponent(jPanelTotalStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)
                        .addComponent(jPanelTotalTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)
                        .addComponent(jPanelTotalClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanelHomeLayout.setVerticalGroup(
            jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHomeLayout.createSequentialGroup()
                .addComponent(jPanelLabelHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addGroup(jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanelTotalClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelTotalStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelTotalTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelStatisticsGender, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelStatisticsAvgScore, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout jPanelContentLayout = new javax.swing.GroupLayout(jPanelContent);
        jPanelContent.setLayout(jPanelContentLayout);
        jPanelContentLayout.setHorizontalGroup(
            jPanelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelContentLayout.setVerticalGroup(
            jPanelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelRightLayout = new javax.swing.GroupLayout(jPanelRight);
        jPanelRight.setLayout(jPanelRightLayout);
        jPanelRightLayout.setHorizontalGroup(
            jPanelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelTop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelContent, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelRightLayout.setVerticalGroup(
            jPanelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRightLayout.createSequentialGroup()
                .addComponent(jPanelTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelMid, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jSplitPane1.setRightComponent(jPanelRight);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 674, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelMenu2jLabelMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMenu2jLabelMenu1MouseClicked
        // TODO add your handling code here:
        jSplitPane1.setDividerLocation(231);
        jLabelLogo1.setVisible(true);
        jLabelTextLogo1.setVisible(true);
        jLabelMenu3.setVisible(true);
        jLabelMenu2.setVisible(false);
    }//GEN-LAST:event_jLabelMenu2jLabelMenu1MouseClicked

    private void jLabelMenu3jLabelMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMenu3jLabelMenuMouseClicked
        // TODO add your handling code here:
        jSplitPane1.setDividerLocation(60);
        jLabelLogo1.setVisible(false);
        jLabelTextLogo1.setVisible(false);
        jLabelMenu3.setVisible(false);
        jLabelMenu2.setVisible(true);
    }//GEN-LAST:event_jLabelMenu3jLabelMenuMouseClicked

    private void jLabelHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelHomeMouseClicked
        // TODO add your handling code here:
        if (jPanelHome != null) {
            jPanelHome.setVisible(true);
            jLabelLineHome.setVisible(true);

            jPStudentManager.setVisible(false);
            jLabelLineStudent.setVisible(false);

            jPTeacherManager.setVisible(false);
            jLabelLineTeacher.setVisible(false);

            jPClassManager.setVisible(false);
            jLabelLineClasses.setVisible(false);

            jPSubjectManager.setVisible(false);
            jLabelLineSubject.setVisible(false);

            jPRoomManager.setVisible(false);
            jLabelLineRoom.setVisible(false);

            jPScoreManager.setVisible(false);
            jLabelLineScore.setVisible(false);

            jPTimetableManager.setVisible(false);
            jLabelLineTimetable.setVisible(false);

            jPUserManager.setVisible(false);
            jLabelLineUser.setVisible(false);
        }
    }//GEN-LAST:event_jLabelHomeMouseClicked

    private void jLabelStudentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelStudentMouseClicked
        // TODO add your handling code here:
        jPStudentManager.setVisible(true);
        jLabelLineStudent.setVisible(true);

        jPTeacherManager.setVisible(false);
        jLabelLineTeacher.setVisible(false);

        jPClassManager.setVisible(false);
        jLabelLineClasses.setVisible(false);

        jPanelHome.setVisible(false);
        jLabelLineHome.setVisible(false);

        jPSubjectManager.setVisible(false);
        jLabelLineSubject.setVisible(false);

        jPRoomManager.setVisible(false);
        jLabelLineRoom.setVisible(false);

        jPScoreManager.setVisible(false);
        jLabelLineScore.setVisible(false);

        jPTimetableManager.setVisible(false);
        jLabelLineTimetable.setVisible(false);

        jPUserManager.setVisible(false);
        jLabelLineUser.setVisible(false);
    }//GEN-LAST:event_jLabelStudentMouseClicked

    private void jLabelShutdownMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelShutdownMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabelShutdownMouseClicked

    private void jLabelHomeMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelHomeMouseMoved
        // TODO add your handling code here:
        jLabelHome.setBackground(new Color(204, 204, 204));
        jLabelHome.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_jLabelHomeMouseMoved

    private void jPanelLeftMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelLeftMouseMoved
        // TODO add your handling code here:
        jLabelHome.setBackground(new Color(255, 255, 255));
        jLabelHome.setForeground(new Color(102, 102, 102));

        jLabelSubject.setBackground(new Color(255, 255, 255));
        jLabelSubject.setForeground(new Color(102, 102, 102));

        jLabelStudent.setBackground(new Color(255, 255, 255));
        jLabelStudent.setForeground(new Color(102, 102, 102));

        jLabelTeacher.setBackground(new Color(255, 255, 255));
        jLabelTeacher.setForeground(new Color(102, 102, 102));

        jLabelTimetable.setBackground(new Color(255, 255, 255));
        jLabelTimetable.setForeground(new Color(102, 102, 102));

        jLabelUser.setBackground(new Color(255, 255, 255));
        jLabelUser.setForeground(new Color(102, 102, 102));

        jLabelClass.setBackground(new Color(255, 255, 255));
        jLabelClass.setForeground(new Color(102, 102, 102));

        jLabelRoom.setBackground(new Color(255, 255, 255));
        jLabelRoom.setForeground(new Color(102, 102, 102));

        jLabelScore.setBackground(new Color(255, 255, 255));
        jLabelScore.setForeground(new Color(102, 102, 102));
    }//GEN-LAST:event_jPanelLeftMouseMoved

    private void jLabelStudentMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelStudentMouseMoved
        // TODO add your handling code here:
        jLabelStudent.setBackground(new Color(204, 204, 204));
        jLabelStudent.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_jLabelStudentMouseMoved

    private void jLabelTeacherMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelTeacherMouseMoved
        // TODO add your handling code here:
        jLabelTeacher.setBackground(new Color(204, 204, 204));
        jLabelTeacher.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_jLabelTeacherMouseMoved

    private void jLabelScoreMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelScoreMouseMoved
        // TODO add your handling code here:
        jLabelScore.setBackground(new Color(204, 204, 204));
        jLabelScore.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_jLabelScoreMouseMoved

    private void jLabelClassMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelClassMouseMoved
        // TODO add your handling code here:
        jLabelClass.setBackground(new Color(204, 204, 204));
        jLabelClass.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_jLabelClassMouseMoved

    private void jLabelSubjectMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSubjectMouseMoved
        // TODO add your handling code here:
        jLabelSubject.setBackground(new Color(204, 204, 204));
        jLabelSubject.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_jLabelSubjectMouseMoved

    private void jLabelTimetableMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelTimetableMouseMoved
        // TODO add your handling code here:
        jLabelTimetable.setBackground(new Color(204, 204, 204));
        jLabelTimetable.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_jLabelTimetableMouseMoved

    private void jLabelRoomMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelRoomMouseMoved
        // TODO add your handling code here:
        jLabelRoom.setBackground(new Color(204, 204, 204));
        jLabelRoom.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_jLabelRoomMouseMoved

    private void jLabelUserMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelUserMouseMoved
        // TODO add your handling code here:
        jLabelUser.setBackground(new Color(204, 204, 204));
        jLabelUser.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_jLabelUserMouseMoved

    private void jLabelTeacherMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelTeacherMouseClicked
        // TODO add your handling code here:
        jPTeacherManager.setVisible(true);
        jLabelLineTeacher.setVisible(true);

        jPStudentManager.setVisible(false);
        jLabelLineStudent.setVisible(false);

        jPClassManager.setVisible(false);
        jLabelLineClasses.setVisible(false);

        jPanelHome.setVisible(false);
        jLabelLineHome.setVisible(false);

        jPSubjectManager.setVisible(false);
        jLabelLineSubject.setVisible(false);

        jPRoomManager.setVisible(false);
        jLabelLineRoom.setVisible(false);

        jPScoreManager.setVisible(false);
        jLabelLineScore.setVisible(false);

        jPTimetableManager.setVisible(false);
        jLabelLineTimetable.setVisible(false);

        jPUserManager.setVisible(false);
        jLabelLineUser.setVisible(false);
    }//GEN-LAST:event_jLabelTeacherMouseClicked

    private void jLabelClassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelClassMouseClicked
        // TODO add your handling code here:
        jPClassManager.setVisible(true);
        jLabelLineClasses.setVisible(true);

        jPStudentManager.setVisible(false);
        jLabelLineStudent.setVisible(false);

        jPTeacherManager.setVisible(false);
        jLabelLineTeacher.setVisible(false);

        jPanelHome.setVisible(false);
        jLabelLineHome.setVisible(false);

        jPSubjectManager.setVisible(false);
        jLabelLineSubject.setVisible(false);

        jPRoomManager.setVisible(false);
        jLabelLineRoom.setVisible(false);

        jPScoreManager.setVisible(false);
        jLabelLineScore.setVisible(false);

        jPTimetableManager.setVisible(false);
        jLabelLineTimetable.setVisible(false);

        jPUserManager.setVisible(false);
        jLabelLineUser.setVisible(false);
    }//GEN-LAST:event_jLabelClassMouseClicked

    private void jLabelSubjectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSubjectMouseClicked
        // TODO add your handling code here:
        jPSubjectManager.setVisible(true);
        jLabelLineSubject.setVisible(true);

        jPClassManager.setVisible(false);
        jLabelLineClasses.setVisible(false);

        jPStudentManager.setVisible(false);
        jLabelLineStudent.setVisible(false);

        jPTeacherManager.setVisible(false);
        jLabelLineTeacher.setVisible(false);

        jPanelHome.setVisible(false);
        jLabelLineHome.setVisible(false);

        jPRoomManager.setVisible(false);
        jLabelLineRoom.setVisible(false);

        jPScoreManager.setVisible(false);
        jLabelLineScore.setVisible(false);

        jPTimetableManager.setVisible(false);
        jLabelLineTimetable.setVisible(false);

        jPUserManager.setVisible(false);
        jLabelLineUser.setVisible(false);
    }//GEN-LAST:event_jLabelSubjectMouseClicked

    private void jLabelRoomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelRoomMouseClicked
        // TODO add your handling code here:
        jPRoomManager.setVisible(true);
        jLabelLineRoom.setVisible(true);

        jPSubjectManager.setVisible(false);
        jLabelLineSubject.setVisible(false);

        jPClassManager.setVisible(false);
        jLabelLineClasses.setVisible(false);

        jPStudentManager.setVisible(false);
        jLabelLineStudent.setVisible(false);

        jPTeacherManager.setVisible(false);
        jLabelLineTeacher.setVisible(false);

        jPanelHome.setVisible(false);
        jLabelLineHome.setVisible(false);

        jPScoreManager.setVisible(false);
        jLabelLineScore.setVisible(false);

        jPTimetableManager.setVisible(false);
        jLabelLineTimetable.setVisible(false);

        jPUserManager.setVisible(false);
        jLabelLineUser.setVisible(false);
    }//GEN-LAST:event_jLabelRoomMouseClicked

    private void jLabelScoreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelScoreMouseClicked
        // TODO add your handling code here:
        jPScoreManager.setVisible(true);
        jLabelLineScore.setVisible(true);

        jPRoomManager.setVisible(false);
        jLabelLineRoom.setVisible(false);

        jPSubjectManager.setVisible(false);
        jLabelLineSubject.setVisible(false);

        jPClassManager.setVisible(false);
        jLabelLineClasses.setVisible(false);

        jPStudentManager.setVisible(false);
        jLabelLineStudent.setVisible(false);

        jPTeacherManager.setVisible(false);
        jLabelLineTeacher.setVisible(false);

        jPanelHome.setVisible(false);
        jLabelLineHome.setVisible(false);

        jPTimetableManager.setVisible(false);
        jLabelLineTimetable.setVisible(false);

        jPUserManager.setVisible(false);
        jLabelLineUser.setVisible(false);
    }//GEN-LAST:event_jLabelScoreMouseClicked

    private void jLabelTimetableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelTimetableMouseClicked
        // TODO add your handling code here:
        jPTimetableManager.setVisible(true);
        jLabelLineTimetable.setVisible(true);

        jPScoreManager.setVisible(false);
        jLabelLineScore.setVisible(false);

        jPRoomManager.setVisible(false);
        jLabelLineRoom.setVisible(false);

        jPSubjectManager.setVisible(false);
        jLabelLineSubject.setVisible(false);

        jPClassManager.setVisible(false);
        jLabelLineClasses.setVisible(false);

        jPStudentManager.setVisible(false);
        jLabelLineStudent.setVisible(false);

        jPTeacherManager.setVisible(false);
        jLabelLineTeacher.setVisible(false);

        jPanelHome.setVisible(false);
        jLabelLineHome.setVisible(false);

        jPUserManager.setVisible(false);
        jLabelLineUser.setVisible(false);
    }//GEN-LAST:event_jLabelTimetableMouseClicked

    private void jLabelUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelUserMouseClicked
        // TODO add your handling code here:
        if (jLabelUser.isEnabled()) {
            jPUserManager.setVisible(true);
            jLabelLineUser.setVisible(true);

            jPTimetableManager.setVisible(false);
            jLabelLineTimetable.setVisible(false);

            jPScoreManager.setVisible(false);
            jLabelLineScore.setVisible(false);

            jPRoomManager.setVisible(false);
            jLabelLineRoom.setVisible(false);

            jPSubjectManager.setVisible(false);
            jLabelLineSubject.setVisible(false);

            jPClassManager.setVisible(false);
            jLabelLineClasses.setVisible(false);

            jPStudentManager.setVisible(false);
            jLabelLineStudent.setVisible(false);

            jPTeacherManager.setVisible(false);
            jLabelLineTeacher.setVisible(false);

            jPanelHome.setVisible(false);
            jLabelLineHome.setVisible(false);
        }
    }//GEN-LAST:event_jLabelUserMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelClass;
    public static javax.swing.JLabel jLabelCountClass;
    public static javax.swing.JLabel jLabelCountStudent;
    public static javax.swing.JLabel jLabelCountTeacher;
    private javax.swing.JLabel jLabelGroup4;
    private javax.swing.JLabel jLabelHome;
    private javax.swing.JLabel jLabelHome1;
    public static javax.swing.JLabel jLabelLineClasses;
    private javax.swing.JLabel jLabelLineHome;
    public static javax.swing.JLabel jLabelLineRoom;
    public static javax.swing.JLabel jLabelLineScore;
    public static javax.swing.JLabel jLabelLineStudent;
    public static javax.swing.JLabel jLabelLineSubject;
    public static javax.swing.JLabel jLabelLineTeacher;
    public static javax.swing.JLabel jLabelLineTimetable;
    public static javax.swing.JLabel jLabelLineUser;
    private javax.swing.JLabel jLabelLogo1;
    private javax.swing.JLabel jLabelMenu2;
    private javax.swing.JLabel jLabelMenu3;
    public static javax.swing.JLabel jLabelRole;
    private javax.swing.JLabel jLabelRoom;
    private javax.swing.JLabel jLabelScore;
    private javax.swing.JLabel jLabelSetting;
    private javax.swing.JLabel jLabelShutdown;
    private javax.swing.JLabel jLabelStudent;
    private javax.swing.JLabel jLabelSubject;
    private javax.swing.JLabel jLabelTeacher;
    private javax.swing.JLabel jLabelTextLogo1;
    private javax.swing.JLabel jLabelTime2;
    private javax.swing.JLabel jLabelTimetable;
    private javax.swing.JLabel jLabelTotalClass;
    private javax.swing.JLabel jLabelTotalStudent;
    private javax.swing.JLabel jLabelTotalTeacher;
    public static javax.swing.JLabel jLabelUser;
    public static javax.swing.JLabel jLabelWelcome;
    public static javax.swing.JPanel jPanelContent;
    public static javax.swing.JPanel jPanelHome;
    private javax.swing.JPanel jPanelLabelHome;
    private javax.swing.JPanel jPanelLeft;
    private javax.swing.JPanel jPanelMid;
    public static javax.swing.JPanel jPanelRight;
    public static javax.swing.JPanel jPanelStatisticsAvgScore;
    public static javax.swing.JPanel jPanelStatisticsGender;
    private javax.swing.JPanel jPanelTop;
    private javax.swing.JPanel jPanelTop1;
    private javax.swing.JPanel jPanelTotalClass;
    private javax.swing.JPanel jPanelTotalStudent;
    private javax.swing.JPanel jPanelTotalTeacher;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
}
